[package]
name = "runes_lib"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.2"
openzeppelin = "0.20.0"
utils = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "dc3d54e84118630efa5e7069eb5c414fd8fbae3f" }
consensus = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "dc3d54e84118630efa5e7069eb5c414fd8fbae3f" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "adf6c44f5c0f8a7fdca30ffb8f1cc79207cb4ae8" }
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "adf6c44f5c0f8a7fdca30ffb8f1cc79207cb4ae8" }

[dev-dependencies]
snforge_std = "0.34.1"
snforge_scarb_plugin = "0.34.1"
assert_macros = "2.11.2"

[scripts]
test = "snforge test"

[lib]
sierra = true
casm = false
